[project]
name = "yt-clip-notes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "humanfriendly>=10.0",
    "moviepy>=2.2.1",
    "pyside6>=6.9.1",
    "yt-dlp>=2025.7.21",
]
